# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt_home.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        if not HomeWindow.objectName():
            HomeWindow.setObjectName(u"HomeWindow")
        HomeWindow.resize(1280, 800)
        HomeWindow.setMinimumSize(QSize(0, 0))
        HomeWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(HomeWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(3, 0))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 648, 224, 141))
        font = QFont()
        font.setFamilies([u"\u5b8b\u4f53"])
        font.setBold(True)
        self.groupBox.setFont(font)
        self.button_print = QPushButton(self.groupBox)
        self.button_print.setObjectName(u"button_print")
        self.button_print.setEnabled(True)
        self.button_print.setGeometry(QRect(127, 96, 74, 37))
        font1 = QFont()
        font1.setFamilies([u"\u5b8b\u4f53"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.button_print.setFont(font1)
        self.separation_1 = QLabel(self.groupBox)
        self.separation_1.setObjectName(u"separation_1")
        self.separation_1.setGeometry(QRect(10, 37, 204, 1))
        self.separation_1.setFont(font)
        self.separation_1.setAutoFillBackground(True)
        self.separation_1.setFrameShape(QFrame.Box)
        self.separation_1.setFrameShadow(QFrame.Raised)
        self.button_ok = QPushButton(self.groupBox)
        self.button_ok.setObjectName(u"button_ok")
        self.button_ok.setEnabled(True)
        self.button_ok.setGeometry(QRect(127, 52, 74, 37))
        self.button_ok.setFont(font1)
        self.button_cancel = QPushButton(self.groupBox)
        self.button_cancel.setObjectName(u"button_cancel")
        self.button_cancel.setEnabled(True)
        self.button_cancel.setGeometry(QRect(20, 52, 74, 37))
        self.button_cancel.setFont(font1)
        self.taps_1 = QLabel(self.groupBox)
        self.taps_1.setObjectName(u"taps_1")
        self.taps_1.setGeometry(QRect(13, 7, 121, 23))
        font2 = QFont()
        font2.setFamilies([u"\u9ed1\u4f53"])
        font2.setPointSize(17)
        font2.setBold(True)
        self.taps_1.setFont(font2)
        self.button_again = QPushButton(self.groupBox)
        self.button_again.setObjectName(u"button_again")
        self.button_again.setEnabled(True)
        self.button_again.setGeometry(QRect(20, 96, 74, 37))
        self.button_again.setFont(font1)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(245, 648, 556, 141))
        self.groupBox_2.setFont(font)
        self.label_result_box = QLabel(self.groupBox_2)
        self.label_result_box.setObjectName(u"label_result_box")
        self.label_result_box.setGeometry(QRect(402, 7, 142, 23))
        self.label_result_box.setFont(font2)
        self.label_result_box.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.separation_2 = QLabel(self.groupBox_2)
        self.separation_2.setObjectName(u"separation_2")
        self.separation_2.setGeometry(QRect(10, 37, 536, 1))
        self.separation_2.setFont(font)
        self.separation_2.setAutoFillBackground(True)
        self.separation_2.setFrameShape(QFrame.Box)
        self.separation_2.setFrameShadow(QFrame.Raised)
        self.taps_2 = QLabel(self.groupBox_2)
        self.taps_2.setObjectName(u"taps_2")
        self.taps_2.setGeometry(QRect(13, 7, 121, 23))
        self.taps_2.setFont(font2)
        self.groupBox_result_1 = QGroupBox(self.groupBox_2)
        self.groupBox_result_1.setObjectName(u"groupBox_result_1")
        self.groupBox_result_1.setGeometry(QRect(13, 45, 34, 90))
        self.groupBox_result_1.setFont(font)
        self.groupBox_result_1.setToolTipDuration(-1)
        self.taps_3 = QLabel(self.groupBox_result_1)
        self.taps_3.setObjectName(u"taps_3")
        self.taps_3.setGeometry(QRect(3, 30, 27, 30))
        font3 = QFont()
        font3.setFamilies([u"\u5b8b\u4f53"])
        font3.setPointSize(21)
        font3.setBold(True)
        self.taps_3.setFont(font3)
        self.taps_3.setAlignment(Qt.AlignCenter)
        self.groupBox_result_2 = QGroupBox(self.groupBox_2)
        self.groupBox_result_2.setObjectName(u"groupBox_result_2")
        self.groupBox_result_2.setGeometry(QRect(68, 45, 34, 90))
        self.groupBox_result_2.setFont(font)
        self.groupBox_result_2.setToolTipDuration(-1)
        self.taps_4 = QLabel(self.groupBox_result_2)
        self.taps_4.setObjectName(u"taps_4")
        self.taps_4.setGeometry(QRect(3, 30, 27, 30))
        self.taps_4.setFont(font3)
        self.taps_4.setAlignment(Qt.AlignCenter)
        self.groupBox_result_3 = QGroupBox(self.groupBox_2)
        self.groupBox_result_3.setObjectName(u"groupBox_result_3")
        self.groupBox_result_3.setGeometry(QRect(123, 45, 34, 90))
        self.groupBox_result_3.setFont(font)
        self.groupBox_result_3.setToolTipDuration(-1)
        self.taps_5 = QLabel(self.groupBox_result_3)
        self.taps_5.setObjectName(u"taps_5")
        self.taps_5.setGeometry(QRect(3, 30, 27, 30))
        self.taps_5.setFont(font3)
        self.taps_5.setAlignment(Qt.AlignCenter)
        self.groupBox_result_4 = QGroupBox(self.groupBox_2)
        self.groupBox_result_4.setObjectName(u"groupBox_result_4")
        self.groupBox_result_4.setGeometry(QRect(178, 45, 34, 90))
        self.groupBox_result_4.setFont(font)
        self.groupBox_result_4.setToolTipDuration(-1)
        self.taps_6 = QLabel(self.groupBox_result_4)
        self.taps_6.setObjectName(u"taps_6")
        self.taps_6.setGeometry(QRect(3, 30, 27, 30))
        self.taps_6.setFont(font3)
        self.taps_6.setAlignment(Qt.AlignCenter)
        self.groupBox_result_5 = QGroupBox(self.groupBox_2)
        self.groupBox_result_5.setObjectName(u"groupBox_result_5")
        self.groupBox_result_5.setGeometry(QRect(233, 45, 34, 90))
        self.groupBox_result_5.setFont(font)
        self.groupBox_result_5.setToolTipDuration(-1)
        self.taps_7 = QLabel(self.groupBox_result_5)
        self.taps_7.setObjectName(u"taps_7")
        self.taps_7.setGeometry(QRect(3, 30, 27, 30))
        self.taps_7.setFont(font3)
        self.taps_7.setAlignment(Qt.AlignCenter)
        self.groupBox_result_8 = QGroupBox(self.groupBox_2)
        self.groupBox_result_8.setObjectName(u"groupBox_result_8")
        self.groupBox_result_8.setGeometry(QRect(398, 45, 34, 90))
        self.groupBox_result_8.setFont(font)
        self.groupBox_result_8.setToolTipDuration(-1)
        self.taps_10 = QLabel(self.groupBox_result_8)
        self.taps_10.setObjectName(u"taps_10")
        self.taps_10.setGeometry(QRect(3, 30, 27, 30))
        self.taps_10.setFont(font3)
        self.taps_10.setAlignment(Qt.AlignCenter)
        self.groupBox_result_7 = QGroupBox(self.groupBox_2)
        self.groupBox_result_7.setObjectName(u"groupBox_result_7")
        self.groupBox_result_7.setGeometry(QRect(343, 45, 34, 90))
        self.groupBox_result_7.setFont(font)
        self.groupBox_result_7.setToolTipDuration(-1)
        self.taps_9 = QLabel(self.groupBox_result_7)
        self.taps_9.setObjectName(u"taps_9")
        self.taps_9.setGeometry(QRect(3, 30, 27, 30))
        self.taps_9.setFont(font3)
        self.taps_9.setAlignment(Qt.AlignCenter)
        self.groupBox_result_6 = QGroupBox(self.groupBox_2)
        self.groupBox_result_6.setObjectName(u"groupBox_result_6")
        self.groupBox_result_6.setGeometry(QRect(288, 45, 34, 90))
        self.groupBox_result_6.setFont(font)
        self.groupBox_result_6.setToolTipDuration(-1)
        self.taps_8 = QLabel(self.groupBox_result_6)
        self.taps_8.setObjectName(u"taps_8")
        self.taps_8.setGeometry(QRect(3, 30, 27, 30))
        self.taps_8.setFont(font3)
        self.taps_8.setAlignment(Qt.AlignCenter)
        self.groupBox_result_9 = QGroupBox(self.groupBox_2)
        self.groupBox_result_9.setObjectName(u"groupBox_result_9")
        self.groupBox_result_9.setGeometry(QRect(453, 45, 34, 90))
        self.groupBox_result_9.setFont(font)
        self.groupBox_result_9.setToolTipDuration(-1)
        self.taps_11 = QLabel(self.groupBox_result_9)
        self.taps_11.setObjectName(u"taps_11")
        self.taps_11.setGeometry(QRect(3, 30, 27, 30))
        self.taps_11.setFont(font3)
        self.taps_11.setAlignment(Qt.AlignCenter)
        self.groupBox_result_10 = QGroupBox(self.groupBox_2)
        self.groupBox_result_10.setObjectName(u"groupBox_result_10")
        self.groupBox_result_10.setGeometry(QRect(508, 45, 34, 90))
        self.groupBox_result_10.setFont(font)
        self.groupBox_result_10.setToolTipDuration(-1)
        self.taps_12 = QLabel(self.groupBox_result_10)
        self.taps_12.setObjectName(u"taps_12")
        self.taps_12.setGeometry(QRect(3, 30, 27, 30))
        self.taps_12.setFont(font3)
        self.taps_12.setAlignment(Qt.AlignCenter)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(814, 11, 464, 782))
        self.groupBox_3.setFont(font)
        self.separation_3 = QLabel(self.groupBox_3)
        self.separation_3.setObjectName(u"separation_3")
        self.separation_3.setGeometry(QRect(10, 37, 445, 1))
        self.separation_3.setFont(font)
        self.separation_3.setAutoFillBackground(True)
        self.separation_3.setFrameShape(QFrame.Box)
        self.separation_3.setFrameShadow(QFrame.Raised)
        self.taps_31 = QLabel(self.groupBox_3)
        self.taps_31.setObjectName(u"taps_31")
        self.taps_31.setGeometry(QRect(20, 7, 121, 23))
        self.taps_31.setFont(font2)
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 52, 145, 69))
        self.groupBox_4.setFont(font)
        self.taps_14 = QLabel(self.groupBox_4)
        self.taps_14.setObjectName(u"taps_14")
        self.taps_14.setGeometry(QRect(20, 7, 101, 23))
        font4 = QFont()
        font4.setFamilies([u"\u5b8b\u4f53"])
        font4.setPointSize(13)
        font4.setBold(True)
        self.taps_14.setFont(font4)
        self.taps_15 = QLabel(self.groupBox_4)
        self.taps_15.setObjectName(u"taps_15")
        self.taps_15.setGeometry(QRect(114, 37, 21, 23))
        self.taps_15.setFont(font1)
        self.label_data_case = QLabel(self.groupBox_4)
        self.label_data_case.setObjectName(u"label_data_case")
        self.label_data_case.setGeometry(QRect(13, 30, 88, 30))
        font5 = QFont()
        font5.setFamilies([u"\u5b8b\u4f53"])
        font5.setPointSize(22)
        font5.setBold(True)
        font5.setUnderline(False)
        self.label_data_case.setFont(font5)
        self.label_data_case.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_5 = QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(161, 52, 145, 69))
        self.groupBox_5.setFont(font)
        self.taps_16 = QLabel(self.groupBox_5)
        self.taps_16.setObjectName(u"taps_16")
        self.taps_16.setGeometry(QRect(20, 7, 114, 23))
        self.taps_16.setFont(font4)
        self.taps_17 = QLabel(self.groupBox_5)
        self.taps_17.setObjectName(u"taps_17")
        self.taps_17.setGeometry(QRect(114, 37, 21, 23))
        self.taps_17.setFont(font1)
        self.label_data_box = QLabel(self.groupBox_5)
        self.label_data_box.setObjectName(u"label_data_box")
        self.label_data_box.setGeometry(QRect(13, 30, 88, 30))
        self.label_data_box.setFont(font5)
        self.label_data_box.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_6 = QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(312, 52, 145, 69))
        self.groupBox_6.setFont(font)
        self.taps_18 = QLabel(self.groupBox_6)
        self.taps_18.setObjectName(u"taps_18")
        self.taps_18.setGeometry(QRect(20, 7, 101, 23))
        self.taps_18.setFont(font4)
        self.taps_19 = QLabel(self.groupBox_6)
        self.taps_19.setObjectName(u"taps_19")
        self.taps_19.setGeometry(QRect(114, 37, 21, 23))
        self.taps_19.setFont(font1)
        self.label_data_unline = QLabel(self.groupBox_6)
        self.label_data_unline.setObjectName(u"label_data_unline")
        self.label_data_unline.setGeometry(QRect(13, 30, 88, 30))
        self.label_data_unline.setFont(font5)
        self.label_data_unline.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton = QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(11, 133, 444, 36))
        self.pushButton.setFont(font1)
        self.taps_13 = QLabel(self.groupBox_3)
        self.taps_13.setObjectName(u"taps_13")
        self.taps_13.setGeometry(QRect(13, 200, 121, 23))
        self.taps_13.setFont(font2)
        self.groupBox_box_0 = QGroupBox(self.groupBox_3)
        self.groupBox_box_0.setObjectName(u"groupBox_box_0")
        self.groupBox_box_0.setGeometry(QRect(107, 254, 255, 45))
        self.groupBox_box_0.setFont(font)
        self.groupBox_box_0.setToolTipDuration(-1)
        self.taps_20 = QLabel(self.groupBox_box_0)
        self.taps_20.setObjectName(u"taps_20")
        self.taps_20.setGeometry(QRect(10, 7, 235, 30))
        font6 = QFont()
        font6.setFamilies([u"\u5b8b\u4f53"])
        font6.setPointSize(17)
        font6.setBold(True)
        self.taps_20.setFont(font6)
        self.taps_20.setAutoFillBackground(False)
        self.taps_20.setAlignment(Qt.AlignCenter)
        self.groupBox_box_1 = QGroupBox(self.groupBox_3)
        self.groupBox_box_1.setObjectName(u"groupBox_box_1")
        self.groupBox_box_1.setGeometry(QRect(20, 342, 190, 40))
        self.groupBox_box_1.setFont(font)
        self.groupBox_box_1.setToolTipDuration(-1)
        self.taps_21 = QLabel(self.groupBox_box_1)
        self.taps_21.setObjectName(u"taps_21")
        self.taps_21.setGeometry(QRect(82, 5, 30, 30))
        self.taps_21.setFont(font3)
        self.taps_21.setAlignment(Qt.AlignCenter)
        self.groupBox_box_2 = QGroupBox(self.groupBox_3)
        self.groupBox_box_2.setObjectName(u"groupBox_box_2")
        self.groupBox_box_2.setGeometry(QRect(253, 342, 190, 40))
        self.groupBox_box_2.setFont(font)
        self.groupBox_box_2.setToolTipDuration(-1)
        self.taps_22 = QLabel(self.groupBox_box_2)
        self.taps_22.setObjectName(u"taps_22")
        self.taps_22.setGeometry(QRect(82, 5, 30, 30))
        self.taps_22.setFont(font3)
        self.taps_22.setAlignment(Qt.AlignCenter)
        self.groupBox_box_3 = QGroupBox(self.groupBox_3)
        self.groupBox_box_3.setObjectName(u"groupBox_box_3")
        self.groupBox_box_3.setGeometry(QRect(20, 432, 190, 40))
        self.groupBox_box_3.setFont(font)
        self.groupBox_box_3.setToolTipDuration(-1)
        self.taps_24 = QLabel(self.groupBox_box_3)
        self.taps_24.setObjectName(u"taps_24")
        self.taps_24.setGeometry(QRect(82, 5, 30, 30))
        self.taps_24.setFont(font3)
        self.taps_24.setAlignment(Qt.AlignCenter)
        self.groupBox_box_4 = QGroupBox(self.groupBox_3)
        self.groupBox_box_4.setObjectName(u"groupBox_box_4")
        self.groupBox_box_4.setGeometry(QRect(251, 432, 190, 40))
        self.groupBox_box_4.setFont(font)
        self.groupBox_box_4.setToolTipDuration(-1)
        self.taps_23 = QLabel(self.groupBox_box_4)
        self.taps_23.setObjectName(u"taps_23")
        self.taps_23.setGeometry(QRect(82, 5, 30, 30))
        self.taps_23.setFont(font3)
        self.taps_23.setAlignment(Qt.AlignCenter)
        self.groupBox_box_5 = QGroupBox(self.groupBox_3)
        self.groupBox_box_5.setObjectName(u"groupBox_box_5")
        self.groupBox_box_5.setGeometry(QRect(20, 523, 190, 40))
        self.groupBox_box_5.setFont(font)
        self.groupBox_box_5.setToolTipDuration(-1)
        self.taps_26 = QLabel(self.groupBox_box_5)
        self.taps_26.setObjectName(u"taps_26")
        self.taps_26.setGeometry(QRect(82, 5, 30, 30))
        self.taps_26.setFont(font3)
        self.taps_26.setAlignment(Qt.AlignCenter)
        self.groupBox_box_6 = QGroupBox(self.groupBox_3)
        self.groupBox_box_6.setObjectName(u"groupBox_box_6")
        self.groupBox_box_6.setGeometry(QRect(251, 523, 190, 40))
        self.groupBox_box_6.setFont(font)
        self.groupBox_box_6.setToolTipDuration(-1)
        self.taps_25 = QLabel(self.groupBox_box_6)
        self.taps_25.setObjectName(u"taps_25")
        self.taps_25.setGeometry(QRect(82, 5, 30, 30))
        self.taps_25.setFont(font3)
        self.taps_25.setAlignment(Qt.AlignCenter)
        self.groupBox_box_7 = QGroupBox(self.groupBox_3)
        self.groupBox_box_7.setObjectName(u"groupBox_box_7")
        self.groupBox_box_7.setGeometry(QRect(20, 614, 190, 40))
        self.groupBox_box_7.setFont(font)
        self.groupBox_box_7.setToolTipDuration(-1)
        self.taps_28 = QLabel(self.groupBox_box_7)
        self.taps_28.setObjectName(u"taps_28")
        self.taps_28.setGeometry(QRect(82, 5, 30, 30))
        self.taps_28.setFont(font3)
        self.taps_28.setAlignment(Qt.AlignCenter)
        self.groupBox_box_8 = QGroupBox(self.groupBox_3)
        self.groupBox_box_8.setObjectName(u"groupBox_box_8")
        self.groupBox_box_8.setGeometry(QRect(251, 614, 190, 40))
        self.groupBox_box_8.setFont(font)
        self.groupBox_box_8.setToolTipDuration(-1)
        self.taps_27 = QLabel(self.groupBox_box_8)
        self.taps_27.setObjectName(u"taps_27")
        self.taps_27.setGeometry(QRect(82, 5, 30, 30))
        self.taps_27.setFont(font3)
        self.taps_27.setAlignment(Qt.AlignCenter)
        self.groupBox_box_9 = QGroupBox(self.groupBox_3)
        self.groupBox_box_9.setObjectName(u"groupBox_box_9")
        self.groupBox_box_9.setGeometry(QRect(20, 704, 190, 40))
        self.groupBox_box_9.setFont(font)
        self.groupBox_box_9.setToolTipDuration(-1)
        self.taps_30 = QLabel(self.groupBox_box_9)
        self.taps_30.setObjectName(u"taps_30")
        self.taps_30.setGeometry(QRect(82, 5, 30, 30))
        self.taps_30.setFont(font3)
        self.taps_30.setAlignment(Qt.AlignCenter)
        self.groupBox_box_10 = QGroupBox(self.groupBox_3)
        self.groupBox_box_10.setObjectName(u"groupBox_box_10")
        self.groupBox_box_10.setGeometry(QRect(251, 704, 190, 40))
        self.groupBox_box_10.setFont(font)
        self.groupBox_box_10.setToolTipDuration(-1)
        self.taps_29 = QLabel(self.groupBox_box_10)
        self.taps_29.setObjectName(u"taps_29")
        self.taps_29.setGeometry(QRect(82, 5, 30, 30))
        self.taps_29.setFont(font3)
        self.taps_29.setAlignment(Qt.AlignCenter)
        self.separation_4 = QLabel(self.groupBox_3)
        self.separation_4.setObjectName(u"separation_4")
        self.separation_4.setGeometry(QRect(10, 229, 445, 1))
        self.separation_4.setFont(font)
        self.separation_4.setAutoFillBackground(True)
        self.separation_4.setFrameShape(QFrame.Box)
        self.separation_4.setFrameShadow(QFrame.Raised)
        self.label_clear = QPushButton(self.groupBox_3)
        self.label_clear.setObjectName(u"label_clear")
        self.label_clear.setGeometry(QRect(375, 4, 67, 31))
        font7 = QFont()
        font7.setFamilies([u"\u5b8b\u4f53"])
        font7.setPointSize(8)
        font7.setBold(True)
        font7.setUnderline(False)
        self.label_clear.setFont(font7)
        self.label_result_case = QLabel(self.centralwidget)
        self.label_result_case.setObjectName(u"label_result_case")
        self.label_result_case.setGeometry(QRect(1122, 214, 142, 23))
        self.label_result_case.setFont(font2)
        self.label_result_case.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 11, 793, 625))
        self.groupBox_7.setFont(font)
        self.label_date = QLabel(self.groupBox_7)
        self.label_date.setObjectName(u"label_date")
        self.label_date.setGeometry(QRect(530, 7, 202, 23))
        self.label_date.setFont(font4)
        self.button_logs = QPushButton(self.groupBox_7)
        self.button_logs.setObjectName(u"button_logs")
        self.button_logs.setGeometry(QRect(370, 0, 67, 37))
        self.button_logs.setFont(font1)
        icon = QIcon(QIcon.fromTheme(u"dialog-warning"))
        self.button_logs.setIcon(icon)
        self.button_logs.setCheckable(False)
        self.button_logs.setChecked(False)
        self.label_title = QLabel(self.groupBox_7)
        self.label_title.setObjectName(u"label_title")
        self.label_title.setGeometry(QRect(0, 0, 255, 37))
        font8 = QFont()
        font8.setFamilies([u"\u9ed1\u4f53"])
        font8.setPointSize(22)
        font8.setBold(True)
        font8.setItalic(False)
        font8.setKerning(True)
        font8.setStyleStrategy(QFont.PreferDefault)
        font8.setHintingPreference(QFont.PreferDefaultHinting)
        self.label_title.setFont(font8)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setTextFormat(Qt.AutoText)
        self.button_Restart = QPushButton(self.groupBox_7)
        self.button_Restart.setObjectName(u"button_Restart")
        self.button_Restart.setGeometry(QRect(209, 0, 67, 37))
        self.button_Restart.setFont(font1)
        icon1 = QIcon(QIcon.fromTheme(u"document-save"))
        self.button_Restart.setIcon(icon1)
        self.button_Restart.setCheckable(False)
        self.button_Restart.setChecked(False)
        self.button_Restart.setAutoRepeat(False)
        self.button_Restart.setAutoExclusive(False)
        self.button_setting = QPushButton(self.groupBox_7)
        self.button_setting.setObjectName(u"button_setting")
        self.button_setting.setGeometry(QRect(450, 0, 67, 37))
        self.button_setting.setFont(font1)
        icon2 = QIcon(QIcon.fromTheme(u"document-properties"))
        self.button_setting.setIcon(icon2)
        self.button_setting.setCheckable(False)
        self.button_setting.setChecked(False)
        self.button_reset = QPushButton(self.groupBox_7)
        self.button_reset.setObjectName(u"button_reset")
        self.button_reset.setGeometry(QRect(290, 0, 67, 37))
        self.button_reset.setFont(font1)
        icon3 = QIcon(QIcon.fromTheme(u"mail-message-new"))
        self.button_reset.setIcon(icon3)
        self.button_reset.setCheckable(False)
        self.button_reset.setChecked(False)
        self.widgetDisplay = QWidget(self.groupBox_7)
        self.widgetDisplay.setObjectName(u"widgetDisplay")
        self.widgetDisplay.setGeometry(QRect(0, 42, 793, 583))
        self.widgetDisplay.setFont(font)
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)

        QMetaObject.connectSlotsByName(HomeWindow)
    # setupUi

    def retranslateUi(self, HomeWindow):
        HomeWindow.setWindowTitle(QCoreApplication.translate("HomeWindow", u"\u626b\u7801\u8bc6\u522b\u7cfb\u7edf", None))
        self.groupBox.setTitle("")
        self.button_print.setText(QCoreApplication.translate("HomeWindow", u"\u6253\u5370\u7bb1\u7801", None))
        self.separation_1.setText("")
        self.button_ok.setText(QCoreApplication.translate("HomeWindow", u"\u786e\u8ba4\u5f55\u5165", None))
        self.button_cancel.setText(QCoreApplication.translate("HomeWindow", u"\u8bbe\u5907\u590d\u4f4d", None))
        self.taps_1.setText(QCoreApplication.translate("HomeWindow", u"\u624b\u52a8\u64cd\u4f5c", None))
        self.button_again.setText(QCoreApplication.translate("HomeWindow", u"\u624b\u52a8\u8bc6\u522b", None))
        self.groupBox_2.setTitle("")
        self.label_result_box.setText(QCoreApplication.translate("HomeWindow", u"\u30100/10\u76d2\u3011", None))
        self.separation_2.setText("")
        self.taps_2.setText(QCoreApplication.translate("HomeWindow", u"\u8bc6\u522b\u7ed3\u679c", None))
        self.groupBox_result_1.setTitle("")
        self.taps_3.setText(QCoreApplication.translate("HomeWindow", u"1", None))
        self.groupBox_result_2.setTitle("")
        self.taps_4.setText(QCoreApplication.translate("HomeWindow", u"2", None))
        self.groupBox_result_3.setTitle("")
        self.taps_5.setText(QCoreApplication.translate("HomeWindow", u"3", None))
        self.groupBox_result_4.setTitle("")
        self.taps_6.setText(QCoreApplication.translate("HomeWindow", u"4", None))
        self.groupBox_result_5.setTitle("")
        self.taps_7.setText(QCoreApplication.translate("HomeWindow", u"5", None))
        self.groupBox_result_8.setTitle("")
        self.taps_10.setText(QCoreApplication.translate("HomeWindow", u"8", None))
        self.groupBox_result_7.setTitle("")
        self.taps_9.setText(QCoreApplication.translate("HomeWindow", u"7", None))
        self.groupBox_result_6.setTitle("")
        self.taps_8.setText(QCoreApplication.translate("HomeWindow", u"6", None))
        self.groupBox_result_9.setTitle("")
        self.taps_11.setText(QCoreApplication.translate("HomeWindow", u"9", None))
        self.groupBox_result_10.setTitle("")
        self.taps_12.setText(QCoreApplication.translate("HomeWindow", u"10", None))
        self.groupBox_3.setTitle("")
        self.separation_3.setText("")
        self.taps_31.setText(QCoreApplication.translate("HomeWindow", u"\u6570\u636e\u7edf\u8ba1", None))
        self.groupBox_4.setTitle("")
        self.taps_14.setText(QCoreApplication.translate("HomeWindow", u"\u5df2\u8bc6\u522b\uff08\u7bb1\uff09", None))
        self.taps_15.setText(QCoreApplication.translate("HomeWindow", u"\u7bb1", None))
        self.label_data_case.setText(QCoreApplication.translate("HomeWindow", u"0", None))
        self.groupBox_5.setTitle("")
        self.taps_16.setText(QCoreApplication.translate("HomeWindow", u"\u5df2\u8bc6\u522b\uff08\u76d2\uff09", None))
        self.taps_17.setText(QCoreApplication.translate("HomeWindow", u"\u76d2", None))
        self.label_data_box.setText(QCoreApplication.translate("HomeWindow", u"0", None))
        self.groupBox_6.setTitle("")
        self.taps_18.setText(QCoreApplication.translate("HomeWindow", u"\u672a\u4e0a\u4f20\u6570\u636e", None))
        self.taps_19.setText(QCoreApplication.translate("HomeWindow", u"\u6761", None))
        self.label_data_unline.setText(QCoreApplication.translate("HomeWindow", u"0", None))
        self.pushButton.setText(QCoreApplication.translate("HomeWindow", u"\u624b\u52a8\u6570\u636e\u4e0a\u4f20", None))
        self.taps_13.setText(QCoreApplication.translate("HomeWindow", u"\u88c5\u7bb1\u8fdb\u5ea6", None))
        self.groupBox_box_0.setTitle("")
        self.taps_20.setText(QCoreApplication.translate("HomeWindow", u"\u8bf7\u6253\u5370\u7bb1\u7801", None))
        self.groupBox_box_1.setTitle("")
        self.taps_21.setText(QCoreApplication.translate("HomeWindow", u"1", None))
        self.groupBox_box_2.setTitle("")
        self.taps_22.setText(QCoreApplication.translate("HomeWindow", u"2", None))
        self.groupBox_box_3.setTitle("")
        self.taps_24.setText(QCoreApplication.translate("HomeWindow", u"3", None))
        self.groupBox_box_4.setTitle("")
        self.taps_23.setText(QCoreApplication.translate("HomeWindow", u"4", None))
        self.groupBox_box_5.setTitle("")
        self.taps_26.setText(QCoreApplication.translate("HomeWindow", u"5", None))
        self.groupBox_box_6.setTitle("")
        self.taps_25.setText(QCoreApplication.translate("HomeWindow", u"6", None))
        self.groupBox_box_7.setTitle("")
        self.taps_28.setText(QCoreApplication.translate("HomeWindow", u"7", None))
        self.groupBox_box_8.setTitle("")
        self.taps_27.setText(QCoreApplication.translate("HomeWindow", u"8", None))
        self.groupBox_box_9.setTitle("")
        self.taps_30.setText(QCoreApplication.translate("HomeWindow", u"9", None))
        self.groupBox_box_10.setTitle("")
        self.taps_29.setText(QCoreApplication.translate("HomeWindow", u"10", None))
        self.separation_4.setText("")
        self.label_clear.setText(QCoreApplication.translate("HomeWindow", u"\u8ba1\u6570\u5f52\u96f6", None))
        self.label_result_case.setText(QCoreApplication.translate("HomeWindow", u"\u30100/10\u6346\u3011", None))
        self.groupBox_7.setTitle("")
        self.label_date.setText("")
        self.button_logs.setText(QCoreApplication.translate("HomeWindow", u"\u65e5\u5fd7", None))
        self.label_title.setText(QCoreApplication.translate("HomeWindow", u"\u626b\u7801\u8bc6\u522b\u7cfb\u7edf", None))
        self.button_Restart.setText(QCoreApplication.translate("HomeWindow", u"\u91cd\u542f", None))
        self.button_setting.setText(QCoreApplication.translate("HomeWindow", u"\u8bbe\u7f6e", None))
        self.button_reset.setText(QCoreApplication.translate("HomeWindow", u"\u91cd\u7f6e", None))
    # retranslateUi

