
;通用配置
[Common]
;保留日志天数
KeepLogDays=7
;日志级别 1:不输出日志;	 2:只输出错误日志;  3:输出错误，警告日志;  4:输出错误，警告，信息日志;   5:输出错误，警告，信息，调试日志;
LogLevel=5
;Http监听端口
Http_ListenPort=http://:9001
;WebSocket监听端口 
WebSocket_ListenPort=ws://:9002
;Tcp监听端口
;Tcp_ListenPort=tcp://:9003
;--



