<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>DSTP2x</artifactId>
        <groupId>com.dascom</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.dascom</groupId>
    <artifactId>DSTP2xDemo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors><descriptor>src/main/assembly/assembly.xml</descriptor></descriptors>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                    <archive>
                        <manifest>
<!--                           change the sample to which you want to test,and package to jar -->
                            <mainClass>com.dstp2x.DrawPrintOnly.Barcode.BarcodeSample</mainClass>
                        </manifest>
                    </archive>
                    <finalName>DSTP2xDemo</finalName>
                </configuration>
            </plugin>


        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.dascom</groupId>
            <artifactId>DSTP2xLib</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.1</version>
        </dependency>
    </dependencies>
</project>